### ***************************
###       S Q L    L A B
###  S T U D E N T    F I L E 
### ***************************

USE supply_chain;


### 1. What is the lowest and highest date in Orders




### 2.	Display month and year wise count of the orders placed



### 3.	Which customers did not place any order.



### 4.	Arrange the products based on high demand by the customer in year 2021.



### 5. Which customer has placed the largest order (i.e. highest order amount)



### 6.	Display top 5 customers in terms of TOTAL amount spent 



### 7.	Find out top 3 suppliers in terms of revenue generated by their products.




### 8.  Create a combined list to display customers and supplier list. The list shall contain following FIVE fields
###     TYPE ('CUSTOMER' or 'SUPPLIER'), Contact Name, City, Country, Phone




### 9. Are there any customers who ordered more than 10 different products in the single order




### 10. Company sells the product at different discounted rates. Refer actual product price in product table 
###    and selling price in the order item table. Find the total amount saved in each order then 
###    display the orders from highest to lowest amount saved. 




### 11.	 List the Suppliers such that there are no customers in the country of the supplier




### 12. Find out for which products, UK is dependent on other countries for the supply. 
###    List the countries which are supplying these products in the same list.




### END
